spring:
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  task:
    scheduling:
      pool:
        size: 2

  file:
    storage-mode: r2

  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

  unis:
    auto-populate-awards: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
